spring.application.name=hospital_management_system

spring.security.user.name=admin
spring.security.user.password=admin

spring.datasource.url=jdbc:postgresql://localhost:5432/hospital-management-system
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=bXlTZWNyZXRLZXlteVNlY3JldEtleW15U2VjcmV0S2V5MTIz
jwt.expiration=3600000


# minor tweak: update verification rules and configs
